# Data Processing

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_table("data/airfoil_self_noise.dat", 
                        header=None, 
                        names=['frequency', 'angle_of_attack', 'chord_length', 'free_stream_velocity', 
                               'suction_side_displacement_thickness', 'scaled_sound_pressure_level'])
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
X

array([[8.00000e+02, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       [1.00000e+03, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       [1.25000e+03, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       ...,
       [4.00000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02],
       [5.00000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02],
       [6.30000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02]])

In [4]:
y

array([126.201, 125.201, 125.951, ..., 106.604, 106.224, 104.204])

## Feature Scaling

In [5]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Training 

In [7]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [8]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[126.27 130.79]
 [120.35 119.54]
 [117.99 110.32]
 [129.19 117.4 ]
 [124.85 127.62]
 [129.19 121.66]
 [120.24 118.69]
 [133.33 130.03]
 [119.55 114.73]
 [126.15 124.21]
 [125.09 125.84]
 [126.82 131.52]
 [132.55 130.7 ]
 [121.13 117.81]
 [123.82 126.66]
 [119.05 113.14]
 [128.76 126.76]
 [123.11 133.38]
 [118.21 118.08]
 [125.28 116.15]
 [122.33 123.46]
 [127.46 130.09]
 [127.43 129.93]
 [126.18 120.66]
 [128.99 134.06]
 [122.75 122.09]
 [116.62 117.09]
 [126.86 138.76]
 [128.15 130.83]
 [126.25 128.24]
 [129.85 128.95]
 [123.96 122.53]
 [109.47 103.38]
 [127.66 126.41]
 [127.9  131.8 ]
 [129.86 130.96]
 [119.82 119.25]
 [103.85 109.64]
 [127.02 127.78]
 [129.85 129.01]
 [131.97 132.54]
 [123.02 125.48]
 [125.11 138.27]
 [118.93 123.13]
 [116.37 111.03]
 [131.46 135.96]
 [126.67 127.12]
 [130.04 129.67]
 [131.82 125.65]
 [123.35 129.24]
 [120.67 123.21]
 [124.53 127.  ]
 [118.56 119.91]
 [124.74 126.56]
 [122.29 121.53]
 [123.66 122.23]
 [113.74 113.3 ]
 [125.74 128.34]
 [124.29 121.7

## Measuring performance

In [9]:
from sklearn.metrics import r2_score 
from sklearn.metrics import mean_squared_error
from sklearn.metrics import median_absolute_error

In [10]:
r2_score(y_test, y_pred)

0.5330694346281187

In [11]:
mean_squared_error(y_test, y_pred)

22.14845512165388

In [12]:
median_absolute_error(y_test, y_pred)

2.7547566225548294