# Data Processing

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_table("data/airfoil_self_noise.dat", 
                        header=None, 
                        names=['frequency', 'angle_of_attack', 'chord_length', 'free_stream_velocity', 
                               'suction_side_displacement_thickness', 'scaled_sound_pressure_level'])
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
X

array([[8.00000e+02, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       [1.00000e+03, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       [1.25000e+03, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       ...,
       [4.00000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02],
       [5.00000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02],
       [6.30000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02]])

In [4]:
y

array([126.201, 125.201, 125.951, ..., 106.604, 106.224, 104.204])

## Feature Scaling

In [5]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Training 

In [7]:
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV

params = {
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'degree': [3, 4, 5],
    'gamma': ['scale', 'auto']
}

regressors = GridSearchCV(estimator=SVR(), param_grid=params, verbose=10)
regressors.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV] degree=3, gamma=scale, kernel=linear ............................
[CV]  degree=3, gamma=scale, kernel=linear, score=0.454, total=   0.0s
[CV] degree=3, gamma=scale, kernel=linear ............................
[CV]  degree=3, gamma=scale, kernel=linear, score=0.398, total=   0.0s
[CV] degree=3, gamma=scale, kernel=linear ............................
[CV]  degree=3, gamma=scale, kernel=linear, score=0.493, total=   0.0s
[CV] degree=3, gamma=scale, kernel=linear ............................
[CV]  degree=3, gamma=scale, kernel=linear, score=0.522, total=   0.0s
[CV] degree=3, gamma=scale, kernel=linear ............................
[CV]  degree=3, gamma=scale, kernel=linear, score=0.556, total=   0.0s
[CV] degree=3, gamma=scale, kernel=poly ..............................
[CV] .. degree=3, gamma=scale, kernel=poly, score=0.474, total=   0.0s
[CV] degree=3, gamma=scale, kernel=poly ..............................
[CV] .. degree=

GridSearchCV(estimator=SVR(),
             param_grid={'degree': [3, 4, 5], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             verbose=10)

## Predicting the Test set results

In [8]:
regressor = regressors.best_estimator_
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[128.74 130.79]
 [119.09 119.54]
 [115.26 110.32]
 [127.15 117.4 ]
 [124.76 127.62]
 [128.71 121.66]
 [119.59 118.69]
 [131.62 130.03]
 [118.4  114.73]
 [126.02 124.21]
 [125.66 125.84]
 [128.97 131.52]
 [130.9  130.7 ]
 [121.8  117.81]
 [125.87 126.66]
 [113.72 113.14]
 [129.33 126.76]
 [127.9  133.38]
 [118.18 118.08]
 [125.74 116.15]
 [121.21 123.46]
 [128.08 130.09]
 [128.62 129.93]
 [124.28 120.66]
 [129.25 134.06]
 [123.33 122.09]
 [117.19 117.09]
 [129.5  138.76]
 [128.79 130.83]
 [127.81 128.24]
 [129.69 128.95]
 [122.1  122.53]
 [110.08 103.38]
 [126.83 126.41]
 [129.11 131.8 ]
 [129.14 130.96]
 [118.5  119.25]
 [117.09 109.64]
 [128.76 127.78]
 [128.28 129.01]
 [130.91 132.54]
 [124.04 125.48]
 [125.49 138.27]
 [120.84 123.13]
 [112.3  111.03]
 [131.59 135.96]
 [127.47 127.12]
 [129.13 129.67]
 [130.58 125.65]
 [124.35 129.24]
 [121.23 123.21]
 [124.54 127.  ]
 [121.04 119.91]
 [127.73 126.56]
 [121.32 121.53]
 [121.71 122.23]
 [117.22 113.3 ]
 [127.82 128.34]
 [122.13 121.7

## Measuring performance

In [9]:
from sklearn.metrics import r2_score 
from sklearn.metrics import mean_squared_error
from sklearn.metrics import median_absolute_error

In [10]:
r2_score(y_test, y_pred)

0.7111707925294724

In [11]:
mean_squared_error(y_test, y_pred)

13.70036835003279

In [12]:
median_absolute_error(y_test, y_pred)

2.097805943941374