# Data Processing

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_table("data/airfoil_self_noise.dat", 
                        header=None, 
                        names=['frequency', 'angle_of_attack', 'chord_length', 'free_stream_velocity', 
                               'suction_side_displacement_thickness', 'scaled_sound_pressure_level'])
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
X

array([[8.00000e+02, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       [1.00000e+03, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       [1.25000e+03, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       ...,
       [4.00000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02],
       [5.00000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02],
       [6.30000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02]])

In [4]:
y

array([126.201, 125.201, 125.951, ..., 106.604, 106.224, 104.204])

## Feature Scaling

In [5]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Training 

In [7]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV

params = {
    'criterion': ['mse', 'friedman_mse', 'mae'],
    'splitter': ['best', 'random'],
    'max_features': [None, 'auto', 'sqrt', 'log2'],
    'random_state': [0]
}

regressors = GridSearchCV(estimator=DecisionTreeRegressor(), param_grid=params, verbose=10)
regressors.fit(X_train, y_train)

tal=   0.0s
[CV] criterion=mse, max_features=auto, random_state=0, splitter=best .
[CV]  criterion=mse, max_features=auto, random_state=0, splitter=best, score=0.800, total=   0.0s
[CV] criterion=mse, max_features=auto, random_state=0, splitter=best .
[CV]  criterion=mse, max_features=auto, random_state=0, splitter=best, score=0.823, total=   0.0s
[CV] criterion=mse, max_features=auto, random_state=0, splitter=best .
[CV]  criterion=mse, max_features=auto, random_state=0, splitter=best, score=0.851, total=   0.0s
[CV] criterion=mse, max_features=auto, random_state=0, splitter=random 
[CV]  criterion=mse, max_features=auto, random_state=0, splitter=random, score=0.792, total=   0.0s
[CV] criterion=mse, max_features=auto, random_state=0, splitter=random 
[CV]  criterion=mse, max_features=auto, random_state=0, splitter=random, score=0.854, total=   0.0s
[CV] criterion=mse, max_features=auto, random_state=0, splitter=random 
[CV]  criterion=mse, max_features=auto, random_state=0, splitter=

GridSearchCV(estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['mse', 'friedman_mse', 'mae'],
                         'max_features': [None, 'auto', 'sqrt', 'log2'],
                         'random_state': [0], 'splitter': ['best', 'random']},
             verbose=10)

## Predicting the Test set results

In [8]:
regressor = regressors.best_estimator_
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[134.56 130.79]
 [117.98 119.54]
 [110.45 110.32]
 [115.85 117.4 ]
 [129.28 127.62]
 [123.56 121.66]
 [119.74 118.69]
 [132.92 130.03]
 [116.3  114.73]
 [125.6  124.21]
 [125.8  125.84]
 [132.18 131.52]
 [132.92 130.7 ]
 [116.56 117.81]
 [126.96 126.66]
 [115.3  113.14]
 [129.04 126.76]
 [134.23 133.38]
 [115.3  118.08]
 [116.07 116.15]
 [120.51 123.46]
 [130.5  130.09]
 [128.54 129.93]
 [134.25 120.66]
 [130.54 134.06]
 [121.66 122.09]
 [112.8  117.09]
 [139.92 138.76]
 [131.02 130.83]
 [130.51 128.24]
 [127.25 128.95]
 [125.47 122.53]
 [104.13 103.38]
 [126.83 126.41]
 [133.77 131.8 ]
 [131.45 130.96]
 [115.66 119.25]
 [112.77 109.64]
 [125.74 127.78]
 [125.45 129.01]
 [132.05 132.54]
 [124.24 125.48]
 [135.32 138.27]
 [121.66 123.13]
 [112.06 111.03]
 [134.23 135.96]
 [126.2  127.12]
 [129.63 129.67]
 [128.43 125.65]
 [129.47 129.24]
 [124.72 123.21]
 [123.86 127.  ]
 [117.33 119.91]
 [127.31 126.56]
 [121.63 121.53]
 [120.47 122.23]
 [117.09 113.3 ]
 [132.36 128.34]
 [121.43 121.7

## Measuring performance

In [9]:
from sklearn.metrics import r2_score 
from sklearn.metrics import mean_squared_error
from sklearn.metrics import median_absolute_error

In [10]:
r2_score(y_test, y_pred)

0.8674075497622166

In [11]:
mean_squared_error(y_test, y_pred)

6.289410356382982

In [12]:
median_absolute_error(y_test, y_pred)

1.437499999999993