# Data Processing

## Importing the libraries

In [76]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Importing the dataset

In [77]:
dataset = pd.read_table("data/airfoil_self_noise.dat", 
                        header=None, 
                        names=['frequency', 'angle_of_attack', 'chord_length', 'free_stream_velocity', 
                               'suction_side_displacement_thickness', 'scaled_sound_pressure_level'])
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [78]:
X

array([[8.00e+02, 0.00e+00, 3.05e-01, 7.13e+01, 2.66e-03],
       [1.00e+03, 0.00e+00, 3.05e-01, 7.13e+01, 2.66e-03],
       [1.25e+03, 0.00e+00, 3.05e-01, 7.13e+01, 2.66e-03],
       ...,
       [4.00e+03, 1.56e+01, 1.02e-01, 3.96e+01, 5.28e-02],
       [5.00e+03, 1.56e+01, 1.02e-01, 3.96e+01, 5.28e-02],
       [6.30e+03, 1.56e+01, 1.02e-01, 3.96e+01, 5.28e-02]])

In [79]:
y

array([126.2 , 125.2 , 125.95, ..., 106.6 , 106.22, 104.2 ])

## Feature Scaling

In [80]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

## Splitting the dataset into the Training set and Test set

In [81]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Training 

In [82]:
tf.random.set_seed(0)

regressor = tf.keras.models.Sequential()
regressor.add(tf.keras.layers.Dense(units=X_train.shape[0], kernel_initializer = 'uniform', activation='relu'))
regressor.add(tf.keras.layers.Dense(units=7, activation='sigmoid'))
# regressor.add(tf.keras.layers.Dense(units=5, activation='relu'))
regressor.add(tf.keras.layers.Dense(units=1))
regressor.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mean_squared_error')

In [92]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor='loss', min_delta=0, patience = 20),#patience=2),
]

In [93]:
regressor.fit(X_train, y_train, batch_size=5, epochs=200, callbacks=callbacks)

Epoch 1/200
226/226 [==============================] - 0s 694us/step - loss: 14858.0703
Epoch 2/200
226/226 [==============================] - 0s 779us/step - loss: 14579.4238
Epoch 3/200
226/226 [==============================] - 0s 673us/step - loss: 14307.7256
Epoch 4/200
226/226 [==============================] - 0s 704us/step - loss: 14040.9482
Epoch 5/200
226/226 [==============================] - 0s 704us/step - loss: 13778.2246
Epoch 6/200
226/226 [==============================] - 0s 686us/step - loss: 13519.2637
Epoch 7/200
226/226 [==============================] - 0s 805us/step - loss: 13263.7734
Epoch 8/200
226/226 [==============================] - 0s 730us/step - loss: 13011.5088
Epoch 9/200
226/226 [==============================] - 0s 664us/step - loss: 12762.4365
Epoch 10/200
226/226 [==============================] - 0s 668us/step - loss: 12516.3154
Epoch 11/200
226/226 [==============================] - 0s 686us/step - loss: 12273.1895
Epoch 12/200
226/226 [========

## Predicting the Test set results

In [94]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[133.13 130.79]
 [120.1  119.54]
 [111.68 110.32]
 [117.23 117.4 ]
 [126.35 127.62]
 [120.75 121.66]
 [120.11 118.69]
 [131.08 130.03]
 [114.1  114.73]
 [125.79 124.21]
 [127.03 125.84]
 [132.12 131.52]
 [131.74 130.7 ]
 [117.87 117.81]
 [126.98 126.66]
 [114.72 113.14]
 [127.69 126.76]
 [132.48 133.38]
 [119.28 118.08]
 [117.22 116.15]
 [121.53 123.46]
 [130.95 130.09]
 [130.71 129.93]
 [122.81 120.66]
 [132.9  134.06]
 [121.62 122.09]
 [115.93 117.09]
 [132.63 138.76]
 [130.8  130.83]
 [130.24 128.24]
 [126.47 128.95]
 [123.88 122.53]
 [103.09 103.38]
 [131.37 126.41]
 [131.47 131.8 ]
 [131.85 130.96]
 [118.63 119.25]
 [112.04 109.64]
 [127.46 127.78]
 [125.77 129.01]
 [132.85 132.54]
 [125.25 125.48]
 [129.88 138.27]
 [122.17 123.13]
 [111.04 111.03]
 [134.1  135.96]
 [129.17 127.12]
 [130.06 129.67]
 [125.49 125.65]
 [127.23 129.24]
 [123.5  123.21]
 [125.77 127.  ]
 [118.35 119.91]
 [126.15 126.56]
 [121.33 121.53]
 [122.71 122.23]
 [114.39 113.3 ]
 [128.06 128.34]
 [122.59 121.7

## Measuring performance

In [95]:
from sklearn.metrics import r2_score 
from sklearn.metrics import mean_squared_error
from sklearn.metrics import median_absolute_error

In [96]:
r2_score(y_test, y_pred)

0.9322909802648519

In [97]:
mean_squared_error(y_test, y_pred)

3.2117198918874075

In [98]:
median_absolute_error(y_test, y_pred)

1.037428344726564