# Data Processing

## Importing the libraries

In [40]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Importing the dataset

In [41]:
dataset = pd.read_table("data/airfoil_self_noise.dat", 
                        header=None, 
                        names=['frequency', 'angle_of_attack', 'chord_length', 'free_stream_velocity', 
                               'suction_side_displacement_thickness', 'scaled_sound_pressure_level'])
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [42]:
X

array([[8.00e+02, 0.00e+00, 3.05e-01, 7.13e+01, 2.66e-03],
       [1.00e+03, 0.00e+00, 3.05e-01, 7.13e+01, 2.66e-03],
       [1.25e+03, 0.00e+00, 3.05e-01, 7.13e+01, 2.66e-03],
       ...,
       [4.00e+03, 1.56e+01, 1.02e-01, 3.96e+01, 5.28e-02],
       [5.00e+03, 1.56e+01, 1.02e-01, 3.96e+01, 5.28e-02],
       [6.30e+03, 1.56e+01, 1.02e-01, 3.96e+01, 5.28e-02]])

In [43]:
y

array([126.2 , 125.2 , 125.95, ..., 106.6 , 106.22, 104.2 ])

## Feature Scaling

In [44]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

## Splitting the dataset into the Training set and Test set

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Training 

In [46]:
tf.random.set_seed(0)

regressor = tf.keras.models.Sequential()
regressor.add(tf.keras.layers.Dense(units=7, activation='sigmoid'))
regressor.add(tf.keras.layers.Dense(units=7, activation='sigmoid'))
regressor.add(tf.keras.layers.Dense(units=5, activation='relu'))
regressor.add(tf.keras.layers.Dense(units=1))
regressor.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), loss='mean_squared_error')

In [47]:
regressor.fit(X_train, y_train, batch_size=5, epochs=50)

Epoch 1/50
226/226 [==============================] - 1s 4ms/step - loss: 12796.8679
Epoch 2/50
226/226 [==============================] - 0s 1ms/step - loss: 602.3802
Epoch 3/50
226/226 [==============================] - 0s 1ms/step - loss: 48.4533
Epoch 4/50
226/226 [==============================] - 0s 1ms/step - loss: 47.8796
Epoch 5/50
226/226 [==============================] - 0s 872us/step - loss: 36.4394
Epoch 6/50
226/226 [==============================] - 0s 704us/step - loss: 23.2498
Epoch 7/50
226/226 [==============================] - 0s 742us/step - loss: 19.4097
Epoch 8/50
226/226 [==============================] - 0s 729us/step - loss: 17.6352
Epoch 9/50
226/226 [==============================] - 0s 822us/step - loss: 17.8475
Epoch 10/50
226/226 [==============================] - 0s 723us/step - loss: 16.3315
Epoch 11/50
226/226 [==============================] - 0s 711us/step - loss: 15.6231
Epoch 12/50
226/226 [==============================] - 0s 717us/step - loss: 1

## Predicting the Test set results

In [48]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[133.05 130.79]
 [121.03 119.54]
 [112.22 110.32]
 [119.59 117.4 ]
 [124.63 127.62]
 [121.59 121.66]
 [118.43 118.69]
 [130.99 130.03]
 [111.93 114.73]
 [124.95 124.21]
 [126.89 125.84]
 [131.08 131.52]
 [131.34 130.7 ]
 [117.41 117.81]
 [127.03 126.66]
 [112.1  113.14]
 [127.03 126.76]
 [131.14 133.38]
 [118.72 118.08]
 [118.92 116.15]
 [119.75 123.46]
 [131.52 130.09]
 [130.86 129.93]
 [122.98 120.66]
 [130.96 134.06]
 [121.32 122.09]
 [113.86 117.09]
 [129.69 138.76]
 [129.85 130.83]
 [129.55 128.24]
 [127.85 128.95]
 [123.19 122.53]
 [108.44 103.38]
 [127.16 126.41]
 [129.74 131.8 ]
 [130.57 130.96]
 [116.79 119.25]
 [108.32 109.64]
 [126.84 127.78]
 [122.7  129.01]
 [132.95 132.54]
 [124.27 125.48]
 [125.58 138.27]
 [116.72 123.13]
 [109.68 111.03]
 [134.35 135.96]
 [129.87 127.12]
 [129.79 129.67]
 [126.75 125.65]
 [127.38 129.24]
 [124.55 123.21]
 [126.5  127.  ]
 [118.77 119.91]
 [128.88 126.56]
 [119.45 121.53]
 [121.22 122.23]
 [112.82 113.3 ]
 [129.52 128.34]
 [121.42 121.7

## Measuring performance

In [49]:
from sklearn.metrics import r2_score 
from sklearn.metrics import mean_squared_error
from sklearn.metrics import median_absolute_error

In [50]:
r2_score(y_test, y_pred)

0.8561708997652258

In [51]:
mean_squared_error(y_test, y_pred)

6.822411313340832

In [52]:
median_absolute_error(y_test, y_pred)

1.4440497436523287