# Data Processing

## Importing the libraries

In [620]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Importing the dataset

In [621]:
dataset = pd.read_table("data/airfoil_self_noise.dat", 
                        header=None, 
                        names=['frequency', 'angle_of_attack', 'chord_length', 'free_stream_velocity', 
                               'suction_side_displacement_thickness', 'scaled_sound_pressure_level'])
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [622]:
X

array([[8.00e+02, 0.00e+00, 3.05e-01, 7.13e+01, 2.66e-03],
       [1.00e+03, 0.00e+00, 3.05e-01, 7.13e+01, 2.66e-03],
       [1.25e+03, 0.00e+00, 3.05e-01, 7.13e+01, 2.66e-03],
       ...,
       [4.00e+03, 1.56e+01, 1.02e-01, 3.96e+01, 5.28e-02],
       [5.00e+03, 1.56e+01, 1.02e-01, 3.96e+01, 5.28e-02],
       [6.30e+03, 1.56e+01, 1.02e-01, 3.96e+01, 5.28e-02]])

In [623]:
y

array([126.2 , 125.2 , 125.95, ..., 106.6 , 106.22, 104.2 ])

## Feature Scaling

In [624]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

## Splitting the dataset into the Training set and Test set

In [625]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Training 

In [626]:
tf.random.set_seed(0)

regressor = tf.keras.models.Sequential()
regressor.add(tf.keras.layers.Dense(units=6, activation='relu'))
regressor.add(tf.keras.layers.Dense(units=7, activation='sigmoid'))
regressor.add(tf.keras.layers.Dense(units=1))
regressor.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), loss='mean_squared_error')

In [627]:
regressor.fit(X_train, y_train, batch_size=5, epochs=50)

Epoch 1/50
226/226 [==============================] - 1s 2ms/step - loss: 14586.6777
Epoch 2/50
226/226 [==============================] - 0s 736us/step - loss: 10670.7212
Epoch 3/50
226/226 [==============================] - 0s 659us/step - loss: 7850.3033
Epoch 4/50
226/226 [==============================] - 0s 655us/step - loss: 5678.9758
Epoch 5/50
226/226 [==============================] - 0s 656us/step - loss: 3963.7582
Epoch 6/50
226/226 [==============================] - 0s 865us/step - loss: 2743.9723
Epoch 7/50
226/226 [==============================] - 0s 717us/step - loss: 1779.0532
Epoch 8/50
226/226 [==============================] - 0s 606us/step - loss: 1127.8020
Epoch 9/50
226/226 [==============================] - 0s 584us/step - loss: 713.0611
Epoch 10/50
226/226 [==============================] - 0s 575us/step - loss: 390.8153
Epoch 11/50
226/226 [==============================] - 0s 588us/step - loss: 230.1465
Epoch 12/50
226/226 [==============================] - 

## Predicting the Test set results

In [628]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[133.63 130.79]
 [119.43 119.54]
 [113.62 110.32]
 [117.32 117.4 ]
 [124.67 127.62]
 [129.17 121.66]
 [118.89 118.69]
 [132.54 130.03]
 [114.57 114.73]
 [125.05 124.21]
 [127.46 125.84]
 [132.27 131.52]
 [132.87 130.7 ]
 [118.01 117.81]
 [128.98 126.66]
 [113.24 113.14]
 [129.16 126.76]
 [132.   133.38]
 [116.57 118.08]
 [119.27 116.15]
 [121.64 123.46]
 [131.02 130.09]
 [130.72 129.93]
 [123.04 120.66]
 [131.06 134.06]
 [120.93 122.09]
 [112.69 117.09]
 [129.05 138.76]
 [129.15 130.83]
 [128.86 128.24]
 [129.15 128.95]
 [121.79 122.53]
 [110.3  103.38]
 [125.55 126.41]
 [129.14 131.8 ]
 [128.74 130.96]
 [116.51 119.25]
 [110.38 109.64]
 [128.96 127.78]
 [127.76 129.01]
 [130.7  132.54]
 [124.47 125.48]
 [124.59 138.27]
 [115.81 123.13]
 [112.37 111.03]
 [133.17 135.96]
 [129.16 127.12]
 [130.16 129.67]
 [129.23 125.65]
 [128.61 129.24]
 [124.22 123.21]
 [126.74 127.  ]
 [116.71 119.91]
 [128.44 126.56]
 [121.18 121.53]
 [122.61 122.23]
 [111.57 113.3 ]
 [128.61 128.34]
 [122.13 121.7

## Measuring performance

In [629]:
from sklearn.metrics import r2_score 
from sklearn.metrics import mean_squared_error
from sklearn.metrics import median_absolute_error

In [630]:
r2_score(y_test, y_pred)

0.7850064094459825

In [631]:
mean_squared_error(y_test, y_pred)

10.198038520002273

In [632]:
median_absolute_error(y_test, y_pred)

1.5844607849121033