# Data Processing

## Importing the libraries

In [99]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Importing the dataset

In [100]:
dataset = pd.read_table("data/airfoil_self_noise.dat", 
                        header=None, 
                        names=['frequency', 'angle_of_attack', 'chord_length', 'free_stream_velocity', 
                               'suction_side_displacement_thickness', 'scaled_sound_pressure_level'])
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [101]:
X

array([[8.00e+02, 0.00e+00, 3.05e-01, 7.13e+01, 2.66e-03],
       [1.00e+03, 0.00e+00, 3.05e-01, 7.13e+01, 2.66e-03],
       [1.25e+03, 0.00e+00, 3.05e-01, 7.13e+01, 2.66e-03],
       ...,
       [4.00e+03, 1.56e+01, 1.02e-01, 3.96e+01, 5.28e-02],
       [5.00e+03, 1.56e+01, 1.02e-01, 3.96e+01, 5.28e-02],
       [6.30e+03, 1.56e+01, 1.02e-01, 3.96e+01, 5.28e-02]])

In [102]:
y

array([126.2 , 125.2 , 125.95, ..., 106.6 , 106.22, 104.2 ])

## Feature Scaling

In [103]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

## Splitting the dataset into the Training set and Test set

In [104]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Training 

In [105]:
tf.random.set_seed(0)

regressor = tf.keras.models.Sequential()
regressor.add(tf.keras.layers.Dense(units=X_train.shape[0], kernel_initializer = 'uniform', activation='relu'))
regressor.add(tf.keras.layers.Dense(units=7, activation='sigmoid'))
# regressor.add(tf.keras.layers.Dense(units=5, activation='relu'))
regressor.add(tf.keras.layers.Dense(units=1))
regressor.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mean_squared_error')

In [106]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor='loss', min_delta=0, patience = 20),#patience=2),
]

In [107]:
regressor.fit(X_train, y_train, batch_size=5, epochs=500, callbacks=callbacks)

2.0823
Epoch 120/500
226/226 [==============================] - 0s 646us/step - loss: 64.0702
Epoch 121/500
226/226 [==============================] - 0s 646us/step - loss: 61.5099
Epoch 122/500
226/226 [==============================] - 0s 757us/step - loss: 57.6002
Epoch 123/500
226/226 [==============================] - 0s 677us/step - loss: 53.2307
Epoch 124/500
226/226 [==============================] - 0s 624us/step - loss: 55.6163
Epoch 125/500
226/226 [==============================] - 0s 655us/step - loss: 50.0681
Epoch 126/500
226/226 [==============================] - 0s 690us/step - loss: 46.8897
Epoch 127/500
226/226 [==============================] - 0s 655us/step - loss: 50.3145
Epoch 128/500
226/226 [==============================] - 0s 721us/step - loss: 48.1680
Epoch 129/500
226/226 [==============================] - 0s 695us/step - loss: 40.0818
Epoch 130/500
226/226 [==============================] - 0s 668us/step - loss: 27.2824
Epoch 131/500
226/226 [=============

## Predicting the Test set results

In [108]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[133.23 130.79]
 [119.34 119.54]
 [110.22 110.32]
 [115.55 117.4 ]
 [127.98 127.62]
 [121.45 121.66]
 [119.21 118.69]
 [127.75 130.03]
 [113.51 114.73]
 [124.1  124.21]
 [126.29 125.84]
 [132.06 131.52]
 [129.94 130.7 ]
 [117.92 117.81]
 [127.95 126.66]
 [114.47 113.14]
 [127.95 126.76]
 [133.76 133.38]
 [118.35 118.08]
 [115.05 116.15]
 [123.21 123.46]
 [129.14 130.09]
 [129.49 129.93]
 [121.72 120.66]
 [132.7  134.06]
 [121.91 122.09]
 [115.89 117.09]
 [135.55 138.76]
 [131.91 130.83]
 [128.58 128.24]
 [125.68 128.95]
 [122.96 122.53]
 [102.88 103.38]
 [124.79 126.41]
 [133.03 131.8 ]
 [130.44 130.96]
 [119.5  119.25]
 [110.48 109.64]
 [126.69 127.78]
 [126.62 129.01]
 [132.64 132.54]
 [124.53 125.48]
 [133.44 138.27]
 [124.17 123.13]
 [111.36 111.03]
 [135.29 135.96]
 [127.53 127.12]
 [129.59 129.67]
 [123.74 125.65]
 [128.47 129.24]
 [120.44 123.21]
 [126.57 127.  ]
 [117.46 119.91]
 [125.67 126.56]
 [121.46 121.53]
 [122.   122.23]
 [112.72 113.3 ]
 [127.06 128.34]
 [122.32 121.7

## Measuring performance

In [109]:
from sklearn.metrics import r2_score 
from sklearn.metrics import mean_squared_error
from sklearn.metrics import median_absolute_error

In [110]:
r2_score(y_test, y_pred)

0.9593702632290961

In [111]:
mean_squared_error(y_test, y_pred)

1.9272370845079945

In [112]:
median_absolute_error(y_test, y_pred)

0.771606506347652